### ISSUE TITLE
[Auth] Google OAuth integration with Neon DB — profile sync & account linking

### ISSUE THREAD

**Issue by sumanthrangausa-06** [sumanthrangausa-06/Rekrut_AI_v2#159]
## Context
Google OAuth login is already implemented in the backend (routes/auth.js) with:
- /api/auth/google/url — initiates OAuth flow
- /api/auth/google/callback — handles callback, creates/links user
- Tokens stored encrypted in oauth_connections table (AES-256-GCM)
- User created with role=candidate by default

## Neon DB Schema — Already Ready ✅
The PostgreSQL database (Neon) already has everything needed for Google OAuth:

- `users.google_id` — added in migration 005b_oauth_refresh_tokens.js
- `users.linkedin_id` — same migration
- `users.avatar_url` — stores profile picture
- `users.oauth_provider` — tracks which provider was used
- `oauth_connections` table — stores encrypted access/refresh tokens with AES-256-GCM
- `oauth_connections.profile_data` — stores full OAuth profile JSON

**No DB migration needed.** The schema is production-ready.

## What's Already There ✅
- OAuth flow complete
- Token encryption at rest
- Auto-create user on first login
- Avatar URL pulled from Google profile
- Login page shows Google button when GOOGLE_CLIENT_ID is configured
- Database schema fully supports OAuth user storage

### 1. Profile Sync from Google
- Pull additional profile fields: name, locale, verified_email
- Update user profile in users table on every login (sync avatar, name)
- Store extended profile data in oauth_connections.profile_data

### 2. Account Linking
- If a user with the same email already exists (password-based), offer to link Google OAuth instead of creating duplicate
- Allow users to connect/disconnect Google from their account settings
- Show connected providers in profile settings

### 3. Recruiter Role via Google OAuth
- Currently all OAuth users default to 'candidate' role
- If user has a company email domain that's already registered, route to join request flow
- If company doesn't exist, prompt for company name and create company (same as email registration)

### 4. Token Refresh
- Google refresh tokens expire or are revoked; handle gracefully
- Use stored refresh_token to get new access_token when needed
- Log token refresh failures for debugging

## Environment Variables Required (You Must Provide These)

**⚠️ Important:** You need to create your own OAuth apps. Neon offers "Managed Better Auth" with shared testing keys, but that requires switching to their auth SDK (@neondatabase/auth). Since Rekrut AI uses a custom auth implementation, you need your own keys.

**Google Cloud Console:**
- `GOOGLE_CLIENT_ID` — Create OAuth 2.0 credentials
- `GOOGLE_CLIENT_SECRET` — From same credentials page
- `GOOGLE_REDIRECT_URI` — e.g. https://rekrutai.co/api/auth/google/callback

**How to get Google keys:**
1. Go to https://console.cloud.google.com/
2. APIs & Services → Credentials → Create OAuth 2.0 Client ID
3. Add authorized redirect URIs: `https://rekrutai.co/api/auth/google/callback`
4. Copy Client ID and Secret to Render env vars

## Alternative: Neon Managed Better Auth (Beta)
Neon offers a managed auth service with shared Google OAuth credentials for testing:
- Enable in Neon Console: Project → Branch → Auth
- Uses `neon_auth` schema instead of custom tables
- **Trade-off:** Requires migrating from custom auth to `@neondatabase/auth` SDK
- **Recommendation:** Not recommended for Rekrut AI at this stage — your custom auth has recruiter-specific logic that Neon Auth doesn't support

## Acceptance Criteria
- [ ] Google profile data syncs to users table on each login
- [ ] Existing email-account users can link Google OAuth
- [ ] Users can disconnect Google from account settings
- [ ] Recruiters can sign up via Google with proper company routing
- [ ] Token refresh is handled silently

## Related
- Existing auth implementation: routes/auth.js
- oauth_connections table: migrations/067_encrypted_oauth_tokens.js
- Sub-issue: #161 (OAuth connection management UI)

**Comment by sumanthrangausa-06** [comment]
## Phase 8: VERIFY Failed

Health gates failed. Relabeling to 'discovered' for re-planning.

### Type Check (client) — ❌ FAILED
- Exit code: 2
- Pre-existing type errors found in codebase (unrelated to #159 changes):
  - : Cannot find name 'RecruiterOmniScorePage'
  - : Property 'phase' does not exist
  - : Expression always truthy
  - : Duplicate identifier 'React'
  - : Property '_isPast' does not exist
  - : Property 'defaultValue' does not exist
  - : Multiple Property errors on ChecklistData type
  - : Property 'verification_request_id' does not exist
  - : Type 'undefined' not assignable (multiple instances)

### Lint (root) — ❌ FAILED
- 863 errors, 407 warnings, 33 infos
- Note: These are pre-existing lint issues across the codebase, not introduced by #159 (which only touched )

### Recommendation
The #159 implementation (routes/auth.js) appears clean. However, the codebase has systemic pre-existing type and lint issues that block Phase 8 verification for ALL issues. Consider:
1. Running a dedicated cleanup issue to fix pre-existing type/lint errors
2. Or adjusting health gate baseline to only check files modified by the issue

Relabeled:  →

**Comment by sumanthrangausa-06** [comment]
## Phase 8: VERIFY Failed

Health gates failed. Relabeling to 'discovered' for re-planning.

### Type Check (client) — ❌ FAILED
- Exit code: 2
- Pre-existing type errors found in codebase (unrelated to #159 changes):
  - `src/App.tsx` line 1324: Cannot find name 'RecruiterOmniScorePage'
  - `src/components/ai-onboarding-dashboard.tsx` line 654: Property 'phase' does not exist
  - `src/components/domain/ai-chat-fab.tsx` line 145: Expression always truthy
  - `src/components/ui/logo.tsx`: Duplicate identifier 'React'
  - `src/pages/candidate/interviews.tsx` line 558: Property '_isPast' does not exist
  - `src/pages/candidate/linkedin-optimizer.tsx` line 229: Property 'defaultValue' does not exist
  - `src/pages/candidate/onboarding.tsx`: Multiple Property errors on ChecklistData type
  - `src/pages/recruiter/background-check.tsx` line 171: Property 'verification_request_id' does not exist
  - `src/pages/recruiter/dashboard.tsx`: Type 'undefined' not assignable (multiple instances)

### Lint (root) — ❌ FAILED
- 863 errors, 407 warnings, 33 infos
- Note: These are pre-existing lint issues across the codebase, not introduced by #159 (which only touched `routes/auth.js`)

### Recommendation
The #159 implementation (routes/auth.js) appears clean. However, the codebase has systemic pre-existing type and lint issues that block Phase 8 verification for ALL issues. Consider:
1. Running a dedicated cleanup issue to fix pre-existing type/lint errors
2. Or adjusting health gate baseline to only check files modified by the issue

Relabeled: ready-for-qa → discovered
