### ISSUE TITLE
fix: Google OAuth 'Invalid OAuth state' on staging

### ISSUE THREAD

**Issue by sumanthrangausa-06** [sumanthrangausa-06/Rekrut_AI_v2#168]
## Bug

Google OAuth login shows **'Invalid OAuth state'** error on staging.

## Root Cause (Diagnosed)

Two issues:

1. **Session cookie `sameSite: 'strict'`** breaks OAuth callbacks
   - When Google redirects back to staging, browser treats it as cross-site
   - `Strict` drops the session cookie → `req.session.oauth_state` is `undefined`
   - Fix: Change to `sameSite: 'lax'` (allows top-level navigation)
   - **Status:** Fixed in dev branch (`ed26e09`)

2. **`GOOGLE_REDIRECT_URI` env var points to `localhost`**
   - `.env`: `GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback`
   - Should be: `https://rekrutai-staging.onrender.com/api/auth/google/callback`
   - Also needs to be added to Google Cloud Console allowed redirect URIs
   - **Status:** PENDING — needs Render env var update

## Fix Checklist

- [x] Change session cookie `sameSite` from `strict` to `lax` in `server.js`
- [ ] Update `GOOGLE_REDIRECT_URI` on Render staging environment
- [ ] Add staging redirect URI to Google Cloud Console OAuth credentials
- [ ] Test Google OAuth flow end-to-end on staging
- [ ] Verify LinkedIn OAuth has same issues (if applicable)

## Files

- `server.js` — session cookie config (line 452)
- `.env` — `GOOGLE_REDIRECT_URI`

**Comment by sumanthrangausa-06** [comment]
## Phase 8 VERIFY Report — Issue #168

### Code Fix Verification ✅

**Fix 1: Session cookie `sameSite: 'lax'` — VERIFIED**
- File: `server.js:552`
- Value: `sameSite: 'lax'` (with explanatory comment: "'lax' required for OAuth callbacks (Google redirects back cross-site)")
- This matches the fix referenced in commit `ed26e09`

**OAuth State Validation — VERIFIED**
- File: `routes/auth.js:536-538`
- Function: `verifyOauthState()` validates `req.session.oauth_state` against callback state parameter
- State is stored in session at auth.js:562 before redirecting to Google

**Redirect URI Fallback Logic — VERIFIED**
- File: `routes/auth.js:548-549`, `:616-617`, `:1189-1190`
- Priority: `GOOGLE_REDIRECT_URI` → `BASE_URL` → `APP_URL` → `req.protocol + host`
- This ensures the redirect URI is correctly derived even if the env var is missing

**Build Gate — PASS ✅**
- Client build: `npm run build` — exited 0, all assets generated with brotli compression

---

### Health Gates (Pre-existing — NOT caused by #168)

| Gate | Command | Result | Notes |
|------|---------|--------|-------|
| Type check | `cd client && npx tsc --noEmit` | ⚠️ Errors visible | Pre-existing TS errors in `candidate/onboarding.tsx`, `recruiter/dashboard.tsx`, etc. |
| Lint (root) | `npx @biomejs/biome check .` | ❌ 925 errors | Pre-existing formatting/lint issues across codebase |
| Lint (client) | `cd client && npx biome check .` | ❌ 705 errors | Pre-existing formatting/lint issues |
| Server tests | `npx jest --testPathPatterns=server/__tests__` | ❌ 4 suites failed | `createRateLimit is not a function` — pre-existing, unrelated |
| Client tests | `cd client && npx vitest run` | ❌ 2 files failed | Pre-existing test failures, unrelated |
| Build | `cd client && npm run build` | ✅ PASS | — |

**None of these failures are related to the OAuth cookie fix.**

---

### Still Pending — Requires Manual Action

The following cannot be verified by the build agent and require manual action by the deployer:

- [ ] **Update `GOOGLE_REDIRECT_URI` env var on Render staging**
  - Target value: `https://rekrutai-staging.onrender.com/api/auth/google/callback`
  - Location: Render Dashboard → rekrutai-dev service → Environment Variables

- [ ] **Add staging redirect URI to Google Cloud Console OAuth credentials**
  - Location: Google Cloud Console → APIs & Services → Credentials → OAuth 2.0 Client IDs
  - Add `https://rekrutai-staging.onrender.com/api/auth/google/callback` to Authorized redirect URIs

- [ ] **Test Google OAuth flow end-to-end on staging**
  - Visit `https://rekrutai-staging.onrender.com/login`
  - Click "Sign in with Google"
  - Complete flow, verify no "Invalid OAuth state" error

- [ ] **Verify LinkedIn OAuth has same issues**
  - Check if LinkedIn callback also uses `sameSite: 'strict'` (already fixed to `lax` in same commit)
  - Verify `LINKEDIN_REDIRECT_URI` points to staging, not localhost

---

### Summary

- ✅ **Code fix verified and correct** — `sameSite: 'lax'` is in place
- ✅ **Build passes**
- ⚠️ **Health gates show pre-existing failures** (unrelated to this issue)
- ⏳ **Environment configuration pending** — needs Render + Google Cloud Console updates before E2E verification

**Recommendation:** Keep issue open until manual env config is complete and E2E OAuth flow is tested on staging. Do not regress to `discovered` — the code fix is done and verified.

**Comment by sumanthrangausa-06** [comment]
## Phase 8 Verification Report (Build Agent)

### Code Fix Verification ✅

| Check | Result | Details |
|-------|--------|---------|
| Session cookie "sameSite" | ✅ VERIFIED | "server.js:552" — "sameSite: 'lax'" with explanatory comment |
| CSRF cookie "sameSite" | ✅ VERIFIED | "server.js:465" — "sameSite: 'lax'" |
| LinkedIn OAuth | ✅ VERIFIED | Uses same session state pattern; fix applies to both |

### Health Gates (Project-wide)

| Gate | Result |
|------|--------|
| Type check | ⚠️ 17 pre-existing errors |
| Lint (root) | ⚠️ 925 errors, 411 warnings |
| Server tests | ⚠️ 4 failed, 1 passed (pre-existing createRateLimit issue) |
| Client tests | ⚠️ 2 failed, 7 passed (pre-existing) |
| Build | ✅ PASSED |

### Infrastructure Status (Blocking Staging Fix)

| Task | Status |
|------|--------|
| Update GOOGLE_REDIRECT_URI on Render staging | ❌ PENDING — requires Render Dashboard |
| Add staging URI to Google Cloud Console | ❌ PENDING — requires Google Cloud Console |
| End-to-end test on staging | ❌ BLOCKED by above |
| Verify LinkedIn OAuth redirect URI | ❌ PENDING — same issue likely |

### Findings

1. **Code fix verified** — "sameSite: 'lax'" correctly set for session + CSRF cookies. Fallback logic for GOOGLE_REDIRECT_URI is robust.
2. **LinkedIn OAuth shares the same vulnerability** — uses "req.session.oauth_state" just like Google.
3. **Staging NOT fully fixed** — Render staging needs GOOGLE_REDIRECT_URI env var set, and URI added to Google Cloud Console.
4. **render.yaml has env var** but "sync: false" means manual Dashboard setup required.

**Code is ready. Infrastructure configuration is the remaining blocker.**
